name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    # Force to use color
    FORCE_COLOR: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install apt packages
        run: |
            sudo -E apt-get -yq update
            sudo -E apt-get -yq --no-install-suggests --no-install-recommends install \
                dvipng texlive-latex-base texlive-latex-extra dvisvgm

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
      - name: Set up Python
        run: uv python install 3.10
      - name: Install Venv
        run: uv venv

      - name: Install Dependencies
        run: uv pip install --resolution lowest-direct -e ".[doc]"

      - name: Build Sphinx documentation
        working-directory: doc
        run: uv run python -m sphinx --builder html . _build/html --verbose --color --fail-on-warning --keep-going --show-traceback --nitpicky

      - name: Upload Sphinx docs artifact
        uses: actions/upload-artifact@v7
        with:
          name: sphinx-docs
          path: doc/_build/html

  deploy:
    # Avoid running this job on a fork
    if: github.repository == 'fmralign/fmralign' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Sphinx docs artifact
        uses: actions/download-artifact@v8
        with:
          name: sphinx-docs
          path: doc/_build/html/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/_build/html
