name: pytest-flake8

on:
    push:
        branches:
        -   main
    pull_request:
        branches:
        -   '*'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run Ruff check
        run: uv run ruff check --output-format=github
      - name: Test with pytest
        run: uv run pytest
