name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v7

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -e ".[test]"

      - name: Test with pytest
        run: uv run pytest --cov --cov-report=xml fmralign

      - name: Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v7
        with:
          flags: py${{ matrix.python-version }}
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false


  test_min:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.10"
          enable-cache: true

      - name: Install dependencies
        run: |
          uv venv
          uv pip install --resolution lowest-direct -e ".[test]"

      - name: Test with pytest
        run: uv run pytest --cov --cov-report=xml
